serviceAccount:
  create: true
  name: expense-api
  annotations:
    azure.workload.identity/client-id: "ded51d97-e258-48ca-8448-e4565311ec78"
workloadIdentity:
  clientId: "ded51d97-e258-48ca-8448-e4565311ec78"

keyVault:
  uri: "https://expensetracker-dev-kv.vault.azure.net/"

auth:
  authority: "https://expensetrackerhqdev.ciamlogin.com/b19bd0da-f1e2-4781-a072-973d388c6016/v2.0"
  audience: "66536591-2962-45c4-9be5-1b100381a561"

podLabels:
  azure.workload.identity/use: "true"
image:
  tag: "430-jwt"   
migrations:
  enabled: true
  image:
    repository: acrexptrackerhqdev01.azurecr.io/expense-migrator
    tag: "dev-20251229-152323"