apiVersion: v1
kind: Service
metadata:
  name: {{ include "expense-api.fullname" . }}
  labels:
    {{- include "expense-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "expense-api.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080