apiVersion: v1
kind: Service
metadata:
  name: expense-api
  labels:
    app: expense-api
spec:
  type: ClusterIP
  selector:
    app: expense-api
  ports:
    - name: http
      port: 80          # service port inside cluster
      targetPort: 8080  # containerPort from your Deployment