apiVersion: v1
kind: Secret
metadata:
  name: expense-api-secrets              
  labels:
    app: expense-api                     
type: Opaque                              
stringData:
  ConnectionStrings__ExpenseTrackerDb: "Server=placeholder;Database=ExpenseTrackerDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
