apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-api-config           
  labels:
    app: expense-api                 
data:
  ASPNETCORE_ENVIRONMENT: "Development"   
  RunMigrations: "false"                  
